"""Declarative base for all ORM models.

Phase 0 had no ORM models (`target_metadata = None` in
`app/db/migrations/env.py`); Phase 1 is the first phase whose application
code reads/writes tables directly, so a real `DeclarativeBase` is
introduced here and wired into `env.py`'s `target_metadata`. The migration
itself (`versions/0002_...py`) stays hand-written (`op.create_table(...)`,
matching `0001`'s style) rather than autogenerated -- these models exist
for the application to use, not to drive `alembic revision --autogenerate`
yet.
"""

from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass
