"""Declarative base for all ORM models.

Phase 0 had no ORM models (`target_metadata = None` in
`app/db/migrations/env.py`); Phase 1 is the first phase whose application
code reads/writes tables directly, so a real `DeclarativeBase` is
introduced here and wired into `env.py`'s `target_metadata`. The migration
itself (`versions/0002_...py`) stays hand-written (`op.create_table(...)`,
matching `0001`'s style) rather than autogenerated -- these models exist
for the application to use, not to drive `alembic revision --autogenerate`
yet.

`type_annotation_map` (doc 17 hotfix): every `Mapped[datetime]` column in
this codebase must be timezone-aware, matching doc 05 §1's stated
convention and what migration `0002` already creates at the SQL level
(`sa.TIMESTAMP(timezone=True)` on every `created_at`/`updated_at`/
`scraped_at` column -- the physical schema was never wrong). Without this
override, SQLAlchemy 2.0's own *default* type_annotation_map sends a bare
`datetime.datetime` annotation to a *naive* `DateTime()` (timezone=False)
-- a client-side-only mismatch against those real timestamptz columns,
invisible until a timezone-aware Python value is actually bound as a
parameter. This codebase uses `datetime.now(UTC)` throughout (see
`app/scraping/fetcher.py`, `NormalizedRecord.scraped_at`), so the mismatch
was real, not theoretical: SQLAlchemy compiled `current_observations`
INSERT/UPDATE statements with a `::TIMESTAMP WITHOUT TIME ZONE` cast on
`scraped_at`'s bind parameter (confirmed from the real failing SQL), and
asyncpg's naive-timestamp codec raised `DataError: can't subtract
offset-naive and offset-aware datetimes` trying to encode a tz-aware
value against it.

Setting the map here, once, means every current *and future*
`Mapped[datetime]` column gets this right by construction -- no need to
remember `DateTime(timezone=True)` on each `mapped_column()` call
individually. No Alembic migration accompanies this fix: the DDL migration
(`0002`) already creates `TIMESTAMP WITH TIME ZONE` columns, so there is
no physical schema to alter -- only the ORM's client-side type was out of
sync with it. `tests/test_models_timezone.py` asserts this directly
(`column.type.timezone is True` for every affected column) without
needing a live database to prove it.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    type_annotation_map = {
        datetime: DateTime(timezone=True),
    }
